require("config.options")
require("config.keymaps")
require("config.autocmds")

-- require("plugins.neodev")
require("plugins.colorscheme")
require("plugins.lastplace")
require("plugins.snacks")
require("plugins.mini")

require("plugins.completion")
require("plugins.Trans")
require("plugins.bufferline")
require("plugins.noice")
require("plugins.lsp")
require("plugins.tabular")
-- require("plugins.telescope")
-- require("plugins.explorer")
