require("config.options")
require("config.keymaps")
require("config.autocmds")

require("plugins.colorscheme")
require("plugins.lastplace")
require("plugins.snacks")
require("plugins.auto-pairs")

require("plugins.completion")
require("plugins.Trans")
require("plugins.bufferline")
require("plugins.noice")
require("plugins.lsp")
require("plugins.tabular")
require("plugins.smart_zero")
